version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      astro:
        patterns:
          - 'astro'
          - '@astrojs/*'
          - 'starlight*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
